name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-20.04]
        os: [windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.14
        with:
          cmake-version: '3.17.x'

      - name: Install doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: '1.9.5'

      - name: Install swig
        run: swig -version
        #uses: johnwason/swig-build-action@v1
        #with:
        #  version: '4.0.2'

      - name: Download openmm
        uses: robinraju/release-downloader@v1.8
        with:
          repository: "openmm/openmm"
          tarBall: true
          latest: true
          extract: true

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1
        if: startsWith(matrix.os, 'windows')

      - name: cmake python package
        if: ${{ runner.os == 'Windows'  }}
        run: |
          cd openmm-openmm-a780005
          mkdir build
          cd build
          cmake ..
          dir
          MSBuild.exe OpenMM.sln /t:Build /p:Configuration=Release
          cmake -DBUILD_TYPE=Release -P cmake_install.cmake
          move python/* ../../
          cd ../../
          dir

      - name: cmake python package
        if: ${{ runner.os != 'Windows' }}
        run: |
          cd openmm-openmm-a780005
          mkdir build
          cd build
          cmake ..
          make
          mv python/* ../../
          cd ../../
          ls -lh

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ARCHS: native
          CIBW_BUILD_VERBOSITY: 3
          CIBW_BUILD: cp310-*
          CIBW_SKIP: pp* *musllinux*
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          #CIBW_BEFORE_BUILD_MACOS:
          CIBW_BEFORE_BUILD: pip install numpy cython
          CIBW_ENVIRONMENT_WINDOWS: OPENMM_INCLUDE_PATH="C:\\Program Files\\OpenMM\\include" OPENMM_LIB_PATH="C:\\Program Files\\OpenMM\\lib"
          CIBW_ENVIRONMENT_LINUX: OPENMM_INCLUDE_PATH=/usr/local/openmm/include OPENMM_LIB_PATH=/usr/local/openmm/lib
          CIBW_BEFORE_BUILD_LINUX: chmod +x install_openmm.sh && ./install_openmm.sh

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl
