name: build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Download openmm
        run: |
          wget https://github.com/openmm/openmm/archive/refs/tags/8.0.0.tar.gz
          tar xzvf 8.0.0.tar.gz
          ls -l

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.x'

      - name: Build Wheels
        uses: pypa/cibuildwheel@v2.13.1
        env:
          CIBW_ARCHS: x86_64
          CIBW_BUILD_VERBOSITY: 1
          CIBW_SKIP: pp* *musllinux*
          #CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          #CIBW_BEFORE_BUILD_MACOS:
          CIBW_BEFORE_BUILD_LINUX: cmake --version

      - run: ls -l wheelhouse

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl

      - name: Deployment
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./wheelhouse/*.whl
